// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbhq4TLyOcgA9LmZz63HNOzHaqUuXrN2A',
    appId: '1:34758612801:web:2c4b8fe1454c307e55f3c0',
    messagingSenderId: '34758612801',
    projectId: 'personaltracker-ebf38',
    authDomain: 'personaltracker-ebf38.firebaseapp.com',
    storageBucket: 'personaltracker-ebf38.firebasestorage.app',
    measurementId: 'G-80HBCDNHLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMELZy6SPabdx9mvstWp-EjQmMPxAe0Ec',
    appId: '1:34758612801:android:c386fe486433176655f3c0',
    messagingSenderId: '34758612801',
    projectId: 'personaltracker-ebf38',
    storageBucket: 'personaltracker-ebf38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Qa_KSbk4uIztY72TznL6mOLoyy1pqHI',
    appId: '1:34758612801:ios:4af899b023cc72f355f3c0',
    messagingSenderId: '34758612801',
    projectId: 'personaltracker-ebf38',
    storageBucket: 'personaltracker-ebf38.firebasestorage.app',
    iosBundleId: 'com.trust.meroapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Qa_KSbk4uIztY72TznL6mOLoyy1pqHI',
    appId: '1:34758612801:ios:4af899b023cc72f355f3c0',
    messagingSenderId: '34758612801',
    projectId: 'personaltracker-ebf38',
    storageBucket: 'personaltracker-ebf38.firebasestorage.app',
    iosBundleId: 'com.trust.meroapp',
  );
}
