name: Deploy Android (Internal testing)

on:
  push:
    branches: [main]

jobs:
  deploy-internal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.4"
          channel: "stable"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Restore Android signing keystore
        run: |
          mkdir -p keys
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keys/upload-keystore.jks

      - name: Write key.properties
        run: |
          cat > android/key.properties <<EOF
          storeFile=../keys/upload-keystore.jks
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF

      - name: Restore Play Store service account key
        run: |
          mkdir -p keys
          echo "${{ secrets.PLAY_STORE_JSON_KEY_BASE64 }}" | base64 -d > keys/play-store-key.json

      - run: flutter pub get

      - name: Deploy to Internal testing
        working-directory: android
        env:
          FVM: "false"
        run: bundle exec fastlane internal
